import { ArrowRight, Check, Globe2, LineChart, ShieldCheck, WalletCards } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

const steps = ['Verify your property and audience', 'Choose formats and category controls', 'Approve campaigns and receive earnings'];

export default function PublishersPage() {
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">Publisher workspace</p><h1 className="mt-4 text-5xl font-semibold tracking-tight text-white">Turn trusted attention into <span className="gradient-text">sustainable revenue.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-neutral-400">Your audience comes first. Set the rules, review every category, and get a clear view of what your inventory earns.</p><div className="mt-8 flex gap-3"><Button>Register a property <ArrowRight className="ml-2 h-4 w-4" /></Button><Link href="/"><Button variant="outline">Learn how it works</Button></Link></div></div><div className="glass p-6 sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs uppercase tracking-[.2em] text-neutral-500">Publisher snapshot</p><h2 className="mt-2 text-xl font-semibold text-white">Dev Studio properties</h2></div><span className="flex items-center gap-2 text-xs text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-300" /> Verified</span></div><div className="grid grid-cols-2 gap-4 py-6"><div><p className="text-xs text-neutral-500">Eligible views</p><p className="mt-1 text-3xl font-semibold text-white">86.4K</p><p className="mt-1 text-xs text-emerald-300">+14.2%</p></div><div><p className="text-xs text-neutral-500">Estimated earnings</p><p className="mt-1 text-3xl font-semibold text-white">$1,248</p><p className="mt-1 text-xs text-neutral-500">This month</p></div></div><div className="space-y-3">{steps.map((step, index) => <div className="flex items-center gap-3 rounded-lg border border-white/10 bg-white/[.03] p-3" key={step}><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-300/10 text-xs text-amber-300">0{index + 1}</span><span className="text-sm text-neutral-300">{step}</span><Check className="ml-auto h-4 w-4 text-emerald-300" /></div>)}</div></div></div><div className="mt-20 grid gap-4 md:grid-cols-3">{[[Globe2, 'Own your surface', 'Decide where ads appear and keep your experience on-brand.'], [ShieldCheck, 'Protect your audience', 'Review advertisers and block categories that do not fit.'], [LineChart, 'See the full picture', 'Understand views, engagement, and earnings in one place.']].map(([Icon, title, text]) => <div className="glass p-6" key={title as string}><Icon className="h-5 w-5 text-amber-300" /><h2 className="mt-5 text-lg font-semibold text-white">{title as string}</h2><p className="mt-2 text-sm leading-6 text-neutral-400">{text as string}</p></div>)}</div><div className="mt-6 flex items-center gap-3 rounded-lg border border-white/10 bg-white/[.02] p-4 text-sm text-neutral-400"><WalletCards className="h-5 w-5 text-amber-300" /> Payouts are reviewed and issued through the network billing workflow.</div></div>;
}
